# Generated by Django 6.1.1 on 2026-09-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='USUARIO',
        ),
    ]
