# Generated by Django 6.1.1 on 2026-09-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('idtipocliente', models.IntegerField(db_column='idTipoCliente', default=1)),
                ('nombrecliente', models.CharField(db_column='nombreCliente', max_length=100)),
                ('nit', models.CharField(blank=True, db_column='nit', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True)),
                ('nombrecontacto', models.CharField(blank=True, db_column='nombreContacto', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('idproductogeneral', models.IntegerField(blank=True, db_column='idProductoGeneral', null=True)),
                ('idpresentacion', models.IntegerField(blank=True, db_column='idPresentacion', null=True)),
                ('idcolor', models.IntegerField(blank=True, db_column='idColor', null=True)),
                ('codigoproducto', models.CharField(blank=True, db_column='codigoProducto', max_length=50, null=True)),
                ('codigobarras', models.CharField(blank=True, db_column='codigoBarras', max_length=50, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idtipocliente', models.AutoField(db_column='idTipoCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'db_table': 'TIPO_CLIENTE',
                'managed': False,
            },
        ),
    ]
